### ISSUE TITLE
loopback device blocks

### ISSUE THREAD

**Issue by josephwinston** [torarnv/sparsebundlefs#10]
On a 32 bit x86 system running an up to date Ubuntu 13.10 and using sparsebundle git commit c89da719579c752ad93dc8520bca7ec72f8f7f26, the loopback device hangs several hours into a copy from the sparse bundle. What information can I provide or what debugging can I do to prevent this from happening?

Enclosed is the first message in syslog.

Dec 27 12:23:55 GT5012 kernel: [82560.924047] INFO: task loop0:15694 blocked for more than 120 seconds.
Dec 27 12:23:55 GT5012 kernel: [82560.924054] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Dec 27 12:23:55 GT5012 kernel: [82560.924059] loop0           D c1260dbb     0 15694      2 0x00000000
Dec 27 12:23:55 GT5012 kernel: [82560.924067]  f408bca4 00000046 f408bc5c c1260dbb f408bc98 00000f44 00000000 c1a3d600
Dec 27 12:23:55 GT5012 kernel: [82560.924078]  00000001 00004af3 c1a3d600 f73e6600 f3f15a20 c12d2122 c1260cf0 f668a878
Dec 27 12:23:55 GT5012 kernel: [82560.924088]  f408bc9c c10a27a8 b62b8e0b 0000d1e4 ffffffff 00000018 488cd38b 0001a64e
Dec 27 12:23:55 GT5012 kernel: [82560.924099] Call Trace:
Dec 27 12:23:55 GT5012 kernel: [82560.924112]  [<c1260dbb>] ? fuse_readpages+0xcb/0xf0
Dec 27 12:23:55 GT5012 kernel: [82560.924121]  [<c12d2122>] ? blk_finish_plug+0x12/0x40
Dec 27 12:23:55 GT5012 kernel: [82560.924127]  [<c1260cf0>] ? fuse_send_readpages.isra.26+0x130/0x130
Dec 27 12:23:55 GT5012 kernel: [82560.924133]  [<c10a27a8>] ? ktime_get_ts+0x48/0x140
Dec 27 12:23:55 GT5012 kernel: [82560.924141]  [<c162a5a6>] io_schedule+0x86/0x100
Dec 27 12:23:55 GT5012 kernel: [82560.924147]  [<c111737d>] sleep_on_page+0xd/0x20
Dec 27 12:23:55 GT5012 kernel: [82560.924154]  [<c16287a9>] __wait_on_bit_lock+0x49/0x90
Dec 27 12:23:55 GT5012 kernel: [82560.924159]  [<c1117370>] ? filemap_fdatawait_range+0x140/0x140
Dec 27 12:23:55 GT5012 kernel: [82560.924164]  [<c1117528>] __lock_page+0x78/0x80
Dec 27 12:23:55 GT5012 kernel: [82560.924170]  [<c1070c60>] ? wake_atomic_t_function+0x50/0x50
Dec 27 12:23:55 GT5012 kernel: [82560.924177]  [<c11913c9>] __generic_file_splice_read+0x5e9/0x5f0
Dec 27 12:23:55 GT5012 kernel: [82560.924183]  [<c118ffa0>] ? page_cache_pipe_buf_release+0x20/0x20
Dec 27 12:23:55 GT5012 kernel: [82560.924191]  [<c104b5de>] ? flush_tlb_func+0x3e/0xa0
Dec 27 12:23:55 GT5012 kernel: [82560.924197]  [<c105764f>] ? irq_exit+0x5f/0xa0
Dec 27 12:23:55 GT5012 kernel: [82560.924203]  [<c1036dd5>] ? smp_call_function_single_interrupt+0x35/0x40
Dec 27 12:23:55 GT5012 kernel: [82560.924209]  [<c162c38c>] ? call_function_single_interrupt+0x34/0x3c
Dec 27 12:23:55 GT5012 kernel: [82560.924215]  [<c104c0e6>] ? kmap_atomic_prot+0x46/0x100
Dec 27 12:23:55 GT5012 kernel: [82560.924221]  [<c127c739>] ? security_file_permission+0x89/0xb0
Dec 27 12:23:55 GT5012 kernel: [82560.924227]  [<c1191463>] generic_file_splice_read+0x93/0xe0
Dec 27 12:23:55 GT5012 kernel: [82560.924233]  [<c11913d0>] ? __generic_file_splice_read+0x5f0/0x5f0
Dec 27 12:23:55 GT5012 kernel: [82560.924238]  [<c119054a>] do_splice_to+0x5a/0x80
Dec 27 12:23:55 GT5012 kernel: [82560.924244]  [<c1190612>] splice_direct_to_actor+0xa2/0x1d0
Dec 27 12:23:55 GT5012 kernel: [82560.924251]  [<c140f510>] ? loop_thread+0x580/0x580
Dec 27 12:23:55 GT5012 kernel: [82560.924257]  [<c140f252>] loop_thread+0x2c2/0x580
Dec 27 12:23:55 GT5012 kernel: [82560.924264]  [<c1079b08>] ? complete+0x48/0x50
Dec 27 12:23:55 GT5012 kernel: [82560.924270]  [<c140ef90>] ? do_lo_send_write+0xd0/0xd0
Dec 27 12:23:55 GT5012 kernel: [82560.924275]  [<c1070114>] kthread+0x94/0xa0
Dec 27 12:23:55 GT5012 kernel: [82560.924280]  [<c1070000>] ? kthread_create_on_node+0x40/0xc0
Dec 27 12:23:55 GT5012 kernel: [82560.924286]  [<c16332b7>] ret_from_kernel_thread+0x1b/0x28
Dec 27 12:23:55 GT5012 kernel: [82560.924291]  [<c1070080>] ? kthread_create_on_node+0xc0/0xc0

**Comment by torarnv** [comment]
Closed due to inactivity.
