### ISSUE TITLE
sparsebundlefs[4000]: segfault at 18 ip 00007f2b36ceb434 sp 00007f2b35e25868 error 4 in libstdc++.so.6.0.17[7f2b36c72000+e8000]

### ISSUE THREAD

**Issue by tmgstevens** [torarnv/sparsebundlefs#12]
sparsebundlefs[4000]: segfault at 18 ip 00007f2b36ceb434 sp 00007f2b35e25868 error 4 in libstdc++.so.6.0.17[7f2b36c72000+e8000]

Don't know if that is enough info to go by - let me know if you'd like me to do anything to help reproduce.

**Comment by torarnv** [comment]
You can also try recompiling with -g and then running like normal, until it locks up, and the attach a debugger and see where it's hanging

**Comment by torarnv** [comment]
Closed due to inactivity.
