### ISSUE TITLE
Permission mismatches

### ISSUE THREAD

**Issue by gusennan** [torarnv/sparsebundlefs#15]
I'm trying to run sparsebundlefs as a non-root user and am unfortunately not able to.  Here's the binary on my system:

```
-rwxrwxr-x 1 nate nate 31427 Mar 14 15:14 ~/tmp/sparsebundlefs
```

Here's the .sparsebundle that I'm trying to mount:

```
drwxr-sr-x 3 nate nate         4096 Mar 14 12:51 mbp-image.sparsebundle
```

Here's the command that I ran:

```
sparsebundlefs mbp-image.sparsebundle mount1
```

mount1 is also owned by me:

```
drwxrwxr-x 2 nate nate         4096 Mar 14 15:59 mount1  
```

But after I run the command, the resulting .dmg is only accessible to root:

```
-r--r--r-- 1 root root 787346657280 Mar 14 12:51 sparsebundle.dmg
```

My user _nate_ is also in the _fuse_ group, if that matters.

Next, when I try to mount the .dmg using the command from the readme (even as sudo), I am not able to because of a permissions denied error.  This is related in #11 .  If I run everything as sudo then I do not have a problem, but I would prefer to not have to.  Thanks for the software, it's very helpful.

**Comment by torarnv** [comment]
Are you still having this issue?

**Comment by gusennan** [comment]
Yes, though I've worked around it just by running everything as su...

**Comment by chriszrc** [comment]
Same here, the resulting directory it creates is very odd:

```
# looking as the user that ran the command
dr-xr-xr-x  3 root root   88 Dec 30 13:22 timemachine/
```

and

```
#looking as root
d?????????  ? ?    ?       ?            ? timemachine/
```
