### ISSUE TITLE
clang compilation warning suggests bug

### ISSUE THREAD

**Issue by jackwasey** [torarnv/sparsebundlefs#16]
`
sparsebundlefs.cpp:298:27: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if (fd_limit.rlim_cur < 0)
`

There are some other clang warnings, but this one suggests a bug

**Comment by torarnv** [comment]
Nice catch! I'll have a look

**Comment by torarnv** [comment]
Fixed in f3ccd20
