### ISSUE TITLE
Wrong total size on 32 bit system

### ISSUE THREAD

**Issue by newca12** [torarnv/sparsebundlefs#26]
Using the same sparse-bundle disk image 

mounted on Debian 9.4 64 bits (work perfectly)
sparsebundlefs: bundle has band size 8388608 and total size 97102254080

mounted on Debian 9.4 32 bits (report wrong total size and of course does not work)
sparsebundlefs: bundle has band size 8388608 and total size 2612973568

**Comment by torarnv** [comment]
Ah, good find!
