### ISSUE TITLE
cp: error reading ...: Input/output error

### ISSUE THREAD

**Issue by eduncan911** [torarnv/sparsebundlefs#28]
sparsebundlefs: master branch as of the time of writing
os: Pop!_OS (aka Ubuntu 18.04)

I have a `sparsebundle` that I created from the macOS command line.  I've used it for years to keep all of my code in one spot, easy to copy to machine to machine with a single file.

At first, I could not use `sparsebundlefs` to mount it, with the error:

    # as root
    mount: /mnt/tmp: failed to setup loop device for /home/eric/code/backup/sparsebundle.dmg.

When dropping the `-o loop` option, I got:

    # as root
    mount: /mnt/tmp: cannot mount /home/eric/code/backup/sparsebundle.dmg read-only.

This was after I ran `sparsebundlefs` under my user space, not root.

----

Unmounting everything, I started over and ran `sparsebundlefs` as root.  This allowed me to mount, as root, in `/mnt/tmp` just fine and I am able to browse and read my files!

Now, I am trying to copy about 20 GB of `git` repos and 1000s of files.  When doing so, I get about 50+ errors of:

``` bash
$ sudo cp -R /mnt/tmp/code/* .
cp: error reading '/mnt/tmp/code/eschalot/wordlist.txt': Input/output error
```
But note, most other files are copied fine - I think (I hope!).

**Comment by torarnv** [comment]
Try running in the foreground with debug logging and see if there are any files that can’t be opened

**Comment by eduncan911** [comment]
I just copied everything manually to an USB stick with verify.  Sorry but I don't have it installed any longer as I formatted to clean the machine clean during the migrations (man, I really miss Qubes).

Closing this for now.
