### ISSUE TITLE
hangs with 100% cpu usage

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [torarnv/sparsebundlefs#29]
I am trying to copy the iso image after the mount with sparsebundlefs
I can copy about 150MB then the system hangs and the CPU is at 100%

if I hit CTRL+C cp terminates but teh CPU remain busy and I can find this on /log/kern.log

`Apr 23 18:46:32 kili kernel: [ 2946.589963] sparsebundlefs[1458]: segfault at 10 ip 00007fed0e5786aa sp 00007fed0c853978 error 4 in libstdc++.so.6.0.25[7fed0e558000+ac000]
Apr 23 18:46:32 kili kernel: [ 2946.590011] Code: 75 94 48 89 71 18 eb 8e 0f 1f 84 00 00 00 00 00 48 39 72 10 0f 84 e6 00 00 00 c7 02 01 00 00 00 48 8b 50 18 c7 00 00 00 00 00 <48> 8b 7a 10 48 89 78 18 48 85 ff 74 04 48 89 47 08 48 8b 78 08 48`

Edoardo Panfili

**Comment by SoftwareIISGubbio** [comment]
after some try it seems that using "rsync --bwlimit=400 -av" instead of "cp" solves the problmen (can't say if the problemes comes from tmfs or sparsebundlefs)

**Comment by torarnv** [comment]
Thanks for your report! Are you able to reproduce the issue with `cp` if you run `sparsebundlefs` with the  `-s` option?

**Comment by torarnv** [comment]
Assumed fixed by 414f30f268ea7 (until we can support multiple threads)
