### ISSUE TITLE
Documentation update needed for Big Sur and apfs

### ISSUE THREAD

**Issue by luzik** [torarnv/sparsebundlefs#36]
APFS is now used as image format

https://eclecticlight.co/2020/06/29/apfs-changes-in-big-sur-how-time-machine-backs-up-to-apfs-and-more/

**Comment by torarnv** [comment]
Thanks. Have you successfully used sparsebundlefs with a mounted APFS image?

**Comment by luzik** [comment]
Sorry, I didn't try
